### ISSUE TITLE
Use “emit” keyword to raise Events

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome#18]
Risk: Medium
Impact: High
Likelihood: Low

Refer to Coinspect Audit Report Issue MTN-006

**Comment by filcap** [comment]
@patidarmanoj10 related to issue #16.  If we consider using pragma 0.4.21, we can add the emit keywords to the contract.

**Comment by patidarmanoj10** [comment]
Emit keyword is added in compiler version 0.4.21 . As of now we can not upgrade to this version for following reasons.
1) Truffle has not released its new version with solc version 0.4.21
2) solhint will also give error with emit keywords as of now hence all pre-commit checks will fail. This too will need updated version of solhint plugin.

**Comment by filcap** [comment]
no action required.
