### ISSUE TITLE
Price is daily auctions does not descend lower than initial supply auction floor

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome#25]
While testing the Metronome wallet, the lowest price, even during the daily auctions was 0.0000033 ETH per MET. Even as minutes passed, the price did not descend with time. 

Expected behavior should be that regardless initial supply auction floor price, during the daily supply lots, the price starts at 2x the closing price of the previous day's auction and descends to 99% of previous price every 60 seconds.

**Comment by patidarmanoj10** [comment]
@filcap @twleung  we can remove floor price check for daily auction but my suggestion would be to keep floor price in daily auction to prevent the MET price set to zero.  This is scenario when there is no buyer for 2-3 days and price will touch zero after reducing it from 1 wei.  Once price set zero it will never increase again ( i.e 2x when starting new auction)even if there is sudden increase in demand.   Please suggest?

**Comment by patidarmanoj10** [comment]
@jgarzik  Please confirm. We may need update in owner's manual and mention floor price for daily auction too.

**Comment by patidarmanoj10** [comment]
My further analysis -  we already adding 1 wei in start price of new auction which can prevent setting price to 0  . Example below line.  
 _startPrice = (lastPurchasePrice * 2) + 1;  
So I think we can safely remove floor price for daily auction and keep it only for initial auction as mentioned in owner's manual. If we want floor price in daily auction then may need update in owner's manual.

**Comment by patidarmanoj10** [comment]
@jgarzik . Gentle reminder. please confirm whether floor price for daily should be 0.0000033 ETH per MET or 1 wei per MET.  We will need change in either owner's manual or source code as per confirmation.

**Comment by patidarmanoj10** [comment]
Fixed.  Daily auction will have floor price 1 wei and initialAuction floor price 0.0000033 ETH
