### ISSUE TITLE
Unclear supply curve specification and implementation

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome#33]
Severity: High
Audit Report: Zeppelin Page 7

**Comment by filcap** [comment]
@patidarmanoj10 , please confirm that this was already resolved in a recent commit.

**Comment by patidarmanoj10** [comment]
We have already implemented this.  Considering the compounding value. Code was committed in this [version](https://github.com/autonomoussoftware/metronome/commit/547291672a21e449d70ac5dbdcffa9efb33b71e1)
