### ISSUE TITLE
Deploy script requires 1000 ETH 

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome#57]
The `initMetronome.js` is executed during contracts deploy. In line `74` is needed to transfer 1000 ETH from the `ETHER_ADDR` to `newOwner` account.

```javascript
var newOwner = personal.newAccount('newOwner')
hash = eth.sendTransaction({to: newOwner, from: ETHER_ADDR, value: web3.toWei(2, 'ether')})
waitForTx(hash)
```

We made some test and 2 ETH (or maybe less) should be enough to perform all operations.

**Comment by patidarmanoj10** [comment]
We have removed this transfer for live and test environment . For local we will still need to make sure new owner has balance.
