### ISSUE TITLE
Deployments to testnet very slow

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome#58]
Deployments to testnet (Ropsten) is very slow, taking hours to complete all steps as some contract creation or initialization transactions take too long to be mined.

Please consider adding options to the deploy scripts (`deploy` and `js/initMetronome.js`) to manipulate the gas price instead of using the default.

**Comment by patidarmanoj10** [comment]
@gabmontes  To be on same page  and reproduce this issue, can you please lets us know what changes you did you did in deploy script to test on ropsten?   trust you had already synced the ropsten node fully before initiating deployment.

**Comment by gabmontes** [comment]
No longer relevant.
