### ISSUE TITLE
Ticker search-and-replace

### ISSUE THREAD

**Issue by jgarzik** [autonomoussoftware/metronome#9]
When ticker is assigned, we must change all symbols with 'MTN' string.

Alternately, we can remove the ticker from strings whereever possible.

**Comment by twleung** [comment]
I think we should remove MTN prefixes from names.   Usually we have a string with the token symbol, which should also get set appropriately.

On Mar 8, 2018, 12:11 PM -0800, Jeff Garzik <notifications@github.com>, wrote:
> When ticker is assigned, we must change all symbols with 'MTN' string.
> Alternately, we can remove the ticker from strings whereever possible.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
*This message and its contents are proprietary and confidential and only 
for its intended recipient. If you received this message in error, do not 
use, forward, copy or rely on it. Instead please notify the sender and then 
delete this message and its attachments, if any. Thank you.*

**Comment by filcap** [comment]
I have already changed the symbol from "MTN" to "MET".   I believe that is the only thing that gets noticed by exchanges.    We can also refactor any contract variables and function names to also reflect, but that would be more for stylistic preference and consistency.

**Comment by filcap** [comment]
https://github.com/autonomoussoftware/metronome/blob/master/contracts/monolithic.sol#L576

**Comment by jgarzik** [comment]
@filcap Mostly agree - it's a bit more than just consistency - we are going through the process of making sure the O.M. API docs are up to date, and there are public functions and symbols containing the older ticker 'MTN' string.  This has already raised questions internally, hence the issue :)

It is certainly a 100% cosmetic change, not a functional change, but it is ABI-visible and needs cleanup before launch.

My recommendation is simply to remove the 'MTN' substring from variable and function names, and not search-and-replace the substring with the new ticker, but I leave that final stylistic choice up to you & the folks.

**Comment by filcap** [comment]
We'll submit a PR shortly

**Comment by patidarmanoj10** [comment]
@filcap , @jgarzik I have sent PR for this item.

**Comment by filcap** [comment]
PR #20 has been merged.
